### ISSUE TITLE
v0.0.37 ,in the use case would happen panic situation

### ISSUE THREAD

**Issue by z9905080** [rueian/rueidis#12]
```
        // client is rueidis client.
	for {
		time.Sleep(1 * time.Second)

		ctx := context.Background()
		resp := client.DoCache(ctx, client.B().Get().Key("abc").Cache(), time.Minute*time.Duration(1))
		if !rueidis.IsRedisNil(resp.Error()) {
			log.Println(resp.ToString())
			continue
		}

		fmt.Printf("Set")
		setErr := client.Do(ctx, client.B().Set().Key("abc").Value("abccc").ExSeconds(int64(3)).Build()).Error()
		if setErr != nil {
			log.Println(setErr)
		}
	}
```
wil get **panic: protocol bug, message handled out of order**

![image](https://user-images.githubusercontent.com/14105056/156490214-9b80bc71-a986-4aba-80c1-10ef3f93c44f.png)

**Comment by rueian** [comment]
Hi @z9905080,

Thank you for filling the issue. I will try to solve this as soon as possible.
Can you give more info about your case? Which Redis version you are using? How long will it take to panic?

**Comment by z9905080** [comment]
> Hi @z9905080,
> 
> Thank you for filling the issue. I will try to solve this as soon as possible. Could you give me more info about your case? Which Redis version you are using? How long will it take to panic?

golang version: 1.17.5
Redis version: 6.2.6
it's no fixed time. looks like happend when set/get the data to redis server and ttl was expired/remove(notify to client side)

environment docker-compose.yml
```
version: '3.9'
services:
  redis-six:
    container_name: redis-six
    image: redis:6.2.6-alpine
    ports:
      - "6379:6379"
    command: redis-server --requirepass password
```
