### ISSUE TITLE
SelectDB doesn't work with a Sentinel Cluster

### ISSUE THREAD

**Issue by rwrz** [rueian/rueidis#138]
I believe when connecting to a Sentinel, the SelectDB should be 0, but then, after getting the client address, it now can use it.

Error:
```
ERR unknown command 'SELECT', with args beginning with: '2' 
```

To replicate:

`docker-compose.yaml`
```yaml
version: "3.5"

services:
  # Redis - Master
  redis:
    image: 'bitnami/redis:latest'
    hostname: redis
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379"
    networks: ["mynetwork"]

 # slaves
  redis-slave:
    image: 'bitnami/redis:latest'
    ports:
      - '6379'
    depends_on:
      - redis
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis
      - ALLOW_EMPTY_PASSWORD=yes
    networks: ["mynetwork"]

  redis-sentinel:
    image: 'bitnami/redis-sentinel:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '26379-26381:26379'
    depends_on:
      - redis
      - redis-slave
    networks: ["mynetwork"]
    
networks:
  mynetwork:
    name: mynetwork
```

`rueidis client`
```go
ruedisClient, err := rueidis.NewClient(rueidis.ClientOption{
	InitAddress: []string{"localhost:26379"},
	Sentinel: rueidis.SentinelOption{
		MasterSet: "mymaster",
	},
	SelectDB: 2, // any number > 0 will give error
})
```
