### ISSUE TITLE
Error connecting to redis 5.0.7 (Ubuntu 20.04)

### ISSUE THREAD

**Issue by kokizzu** [rueian/rueidis#88]
It returns `ERR unknown command `HELLO`, with args beginning with: `3`,`

docker compose:
```
version: '3.7'

services:
    
  # REDIS: 3 MB
  redis1:
    image: redis:5.0.7
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - ./tmp/redis:/data
    restart: unless-stopped

volumes:
  redisdata1:
```

code to reproduce:
```
package main
import "fmt"
import redis "github.com/rueian/rueidis"

func main() {
	conn, err := redis.NewClient(redis.ClientOption{
		InitAddress: []string{`127.0.0.1:6379`},
		Password:    ``,
		SelectDB:    4,
	})
	fmt.Println(conn,err)
}
```

go mod:
```
module d

go 1.19

require github.com/rueian/rueidis v0.0.73
```
